name: 'Generate deploy button'
description: 'Generate the deploy button'
author: 'Vibou'
inputs:
  deploy_id:
    description: 'the deploy id'
    required: true
  deploy_env:
    description: 'Which environment is targeted for the deployment'
    required: false
    default: 'prod'
  deploy_type:
    description: 'model if deploying AI model'
    required: false
    default: ''

outputs:
  release-button:
    description: The resulting deploy button markdown

runs:
  using: 'node12'
  main: './lib/deploy_button.js'
